
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package roxysoft;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import java.util.regex.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
    
    
    
    
    
    
       

    
    /**
 *
 * @author mark
 */


public class sell extends javax.swing.JFrame {
    private double subnum;
    private String whatShow = "1stShowing";
    private int firstshow;
    private int secondshow;
    private int thirdshow;
    private int fourthshow;
  

    /**
     * Creates new form sell
     */
    public sell() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        kd = new javax.swing.JButton();
        sd = new javax.swing.JButton();
        md = new javax.swing.JButton();
        ld = new javax.swing.JButton();
        w = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        subtotalarea = new javax.swing.JTextArea();
        kp = new javax.swing.JButton();
        sp = new javax.swing.JButton();
        mp = new javax.swing.JButton();
        sc = new javax.swing.JButton();
        mc = new javax.swing.JButton();
        lc = new javax.swing.JButton();
        lcombo = new javax.swing.JButton();
        kcombo = new javax.swing.JButton();
        scombo = new javax.swing.JButton();
        kr = new javax.swing.JButton();
        mr = new javax.swing.JButton();
        semp = new javax.swing.JButton();
        memp = new javax.swing.JButton();
        lemp = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        tenderbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        subtotalbox = new javax.swing.JTextField();
        changebox = new javax.swing.JTextField();
        buck = new javax.swing.JButton();
        twentybucks = new javax.swing.JButton();
        fivebucks = new javax.swing.JButton();
        tenbucks = new javax.swing.JButton();
        fiftybucks = new javax.swing.JButton();
        done = new javax.swing.JButton();
        rticket = new javax.swing.JButton();
        sticket = new javax.swing.JButton();
        mdiscount = new javax.swing.JButton();
        kticket = new javax.swing.JButton();
        monster = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        secondShowing = new javax.swing.JButton();
        thirdShowing = new javax.swing.JButton();
        forthShowing = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        canbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roxysoft");
        setFocusTraversalPolicyProvider(true);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kd.setText("Kids Drink");
        kd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdActionPerformed(evt);
            }
        });

        sd.setText("Small Drink");
        sd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdActionPerformed(evt);
            }
        });

        md.setText("Med Drink");
        md.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdActionPerformed(evt);
            }
        });

        ld.setText("Large Drink");
        ld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldActionPerformed(evt);
            }
        });

        w.setText("Water");
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });

        subtotalarea.setColumns(20);
        subtotalarea.setRows(5);
        jScrollPane1.setViewportView(subtotalarea);

        kp.setText("Kids Popcorn");
        kp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpActionPerformed(evt);
            }
        });

        sp.setText("Med Popcorn");
        sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spActionPerformed(evt);
            }
        });

        mp.setText("Large Popcorn");
        mp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpActionPerformed(evt);
            }
        });

        sc.setText("$1 Candy");
        sc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scActionPerformed(evt);
            }
        });

        mc.setText("$2 Candy");
        mc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcActionPerformed(evt);
            }
        });

        lc.setText("$3 Candy");
        lc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcActionPerformed(evt);
            }
        });

        lcombo.setText("Large Combo");
        lcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcomboActionPerformed(evt);
            }
        });

        kcombo.setText("Kids Combo");
        kcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kcomboActionPerformed(evt);
            }
        });

        scombo.setText("Super Combo");
        scombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scomboActionPerformed(evt);
            }
        });

        kr.setText("Kids refil");
        kr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krActionPerformed(evt);
            }
        });

        mr.setText("Small Med Refil");
        mr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrActionPerformed(evt);
            }
        });

        semp.setText("EMP $1");
        semp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sempActionPerformed(evt);
            }
        });

        memp.setText("EMP $2");
        memp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mempActionPerformed(evt);
            }
        });

        lemp.setText("EMP $3");
        lemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lempActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        tenderbox.setText(" ");

        jLabel1.setText("Tender");

        jLabel2.setText("Subtotal");

        jButton2.setText("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        changebox.setText(" ");

        buck.setText("$1");
        buck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buckActionPerformed(evt);
            }
        });

        twentybucks.setText("$20");
        twentybucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentybucksActionPerformed(evt);
            }
        });

        fivebucks.setText("$5");
        fivebucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivebucksActionPerformed(evt);
            }
        });

        tenbucks.setText("$10");
        tenbucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenbucksActionPerformed(evt);
            }
        });

        fiftybucks.setText("$50");
        fiftybucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiftybucksActionPerformed(evt);
            }
        });

        done.setText("Next!");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        rticket.setText("Reg Ticket");
        rticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rticketActionPerformed(evt);
            }
        });

        sticket.setText("Senior Ticket");
        sticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sticketActionPerformed(evt);
            }
        });

        mdiscount.setText("Military Ticket");
        mdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdiscountActionPerformed(evt);
            }
        });

        kticket.setText("Kids Ticket");
        kticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kticketActionPerformed(evt);
            }
        });

        monster.setText("Monster");
        monster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monsterActionPerformed(evt);
            }
        });

        jButton3.setText("1st Showing");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        secondShowing.setText("2nd Showing");
        secondShowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondShowingActionPerformed(evt);
            }
        });

        thirdShowing.setText("3rd Showing");
        thirdShowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdShowingActionPerformed(evt);
            }
        });

        forthShowing.setText("4th Showing");
        forthShowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forthShowingActionPerformed(evt);
            }
        });

        cancel.setText("Subtract");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel3.setText("$ to cancel from total");

        jLabel4.setText("To null ticket, erase. Or disfigure show time and ticket type");

        jMenu1.setText("ROXYSOFT");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondShowing)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thirdShowing)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(forthShowing)
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buck, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(fivebucks, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(twentybucks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(subtotalbox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(tenbucks, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tenderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cancel)
                                            .addComponent(canbox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fiftybucks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(changebox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(md, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ld, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(monster)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(sp)
                                        .addGap(175, 175, 175)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(kticket, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(mdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(sticket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(rticket, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addComponent(jScrollPane1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(260, 260, 260)
                                        .addComponent(mp)
                                        .addGap(41, 41, 41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(semp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(memp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lemp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kr, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mr, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(lc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(scombo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(kcombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(795, 795, 795)))
                        .addGap(12, 12, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(455, 455, 455))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lemp, memp, semp});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {kd, kp, lc, ld, mc, md, mp, sc, sd, sp});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(monster, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(md, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(ld, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 41, Short.MAX_VALUE)
                                .addComponent(rticket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sticket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kticket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buck)
                            .addComponent(tenbucks)
                            .addComponent(jLabel1)
                            .addComponent(canbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twentybucks)
                            .addComponent(fivebucks)
                            .addComponent(subtotalbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(fiftybucks)
                            .addComponent(changebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jButton3)
                            .addComponent(secondShowing)
                            .addComponent(thirdShowing)
                            .addComponent(forthShowing)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(semp)
                                    .addComponent(memp)
                                    .addComponent(lemp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kr)
                                    .addComponent(mr)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(scombo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {kcombo, kd, kp, lc, ld, mc, md, mp, sc, sd, sp});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lemp, memp, semp});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {kticket, mdiscount, rticket, sticket});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:

        this.tenderbox.setText(" ");
        this.subtotalbox.setText(" ");
        this.subtotalarea.setText(" ");
        this.changebox.setText(" ");
        subnum=0;
        
    }//GEN-LAST:event_clearActionPerformed

    private void mrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "small medium refill "+"$1.00");
        subnum = subnum + 1.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mrActionPerformed

    private void krActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Kids refil "+"$0.50");
        subnum = subnum + 0.50 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_krActionPerformed

    private void fiftybucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiftybucksActionPerformed
        // TODO add your handling code here:
        Double tbox = 50.00;
        this.tenderbox.setText(""+tbox);
    }//GEN-LAST:event_fiftybucksActionPerformed

    private void twentybucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentybucksActionPerformed
        // TODO add your handling code here:
        Double tbox = 20.00;
        this.tenderbox.setText(""+tbox);
    }//GEN-LAST:event_twentybucksActionPerformed

    private void kticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kticketActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + whatShow + " Kids "+"$0.00");
        subnum = subnum + 0.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_kticketActionPerformed

    private void sticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sticketActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + whatShow + " Senior Ticket "+"$4.00");
        subnum = subnum + 4.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_sticketActionPerformed

    private void rticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rticketActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + whatShow +" Regular Ticket "+"$5.00");
        subnum = subnum + 5.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_rticketActionPerformed

    private void lempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lempActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$3.00 EMP "+"$1.50");
        subnum = subnum + 1.50 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_lempActionPerformed

    private void mempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mempActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$2.00 EMP"+"$1.00");
        subnum = subnum + 1.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mempActionPerformed

    private void sempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sempActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$1:00 EMP"+"$.50");
        subnum = subnum + 0.50 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_sempActionPerformed

    private void scomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scomboActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Super Combo "+"$10.00");
        subnum = subnum + 10;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_scomboActionPerformed

    private void lcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcomboActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Large Combo "+"$7.75");
        subnum = subnum + 7.75 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_lcomboActionPerformed

    private void kcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kcomboActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Kids Combo "+"$3.25");
        subnum = subnum + 3.25 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_kcomboActionPerformed

    private void lcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$3.00 Candy "+"$3.00");
        subnum = subnum + 3.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_lcActionPerformed

    private void mcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$2.00 Candy "+"$2.00");
        subnum = subnum + 2.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mcActionPerformed

    private void scActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$1.00 Candy "+"$1.00");
        subnum = subnum + 1.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_scActionPerformed

    private void kpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kpActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Kids Popcorn "+"$1.75");
        subnum = subnum + 1.75 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_kpActionPerformed

    private void spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Med Popcorn "+"$4.00");
        subnum = subnum + 4.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_spActionPerformed

    private void mpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Large Popcorn "+"$4.50");
        subnum = subnum + 4.50;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mpActionPerformed

    private void wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Water "+"$1.25");
        subnum = subnum + 1.25 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_wActionPerformed

    private void ldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Large Drink "+"$4.00");
        subnum = subnum + 4.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_ldActionPerformed

    private void mdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Med Drink "+"$3.50");
        subnum = subnum + 3.50;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mdActionPerformed

    private void sdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdActionPerformed
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Small Drink "+"$2.75");
        subnum = subnum + 2.75 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_sdActionPerformed

    private void kdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdActionPerformed
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Kids Drink "+"$1.25");
        subnum = subnum + 1.25 ;

        this.subtotalbox.setText(" "+subnum);
    }//GEN-LAST:event_kdActionPerformed

    private void tenbucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenbucksActionPerformed
        // TODO add your handling code here:
        Double tbox = 10.00;
        this.tenderbox.setText(""+tbox);
    }//GEN-LAST:event_tenbucksActionPerformed

    private void fivebucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivebucksActionPerformed
        // TODO add your handling code here:
        Double tbox = 5.00;
        this.tenderbox.setText(""+tbox);
    }//GEN-LAST:event_fivebucksActionPerformed

    private void buckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buckActionPerformed
        // TODO add your handling code here:
        Double tbox = 1.00;
        this.tenderbox.setText(""+tbox);
    }//GEN-LAST:event_buckActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        PrintWriter out = null;
        try {
            out = new PrintWriter(new FileWriter("roxyrecord.txt", true));
           //worked! works! Whooot
            String subbtt = this.subtotalarea.getText();
            String stuff =subbtt+"\n"+"\n"+"SubTotal:"+subnum;
            
            out.println(stuff);
            out.close();
            
            
            
            this.tenderbox.setText(" ");
            this.subtotalbox.setText(" ");
            this.subtotalarea.setText(" ");
            this.changebox.setText(" ");
            subnum=0;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(sell.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(sell.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_doneActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // This is the Change button Sorry
                  String t;
                  String m;
                  Double chg;
                  t = this.tenderbox.getText();
                  m = this.subtotalbox.getText();
                 Double dObj1 = new Double(t);
                 Double dObj2 = new Double(m);
                  
                 chg = dObj1-dObj2;
                 
               String cg = Double.toString(chg);
                this.changebox.setText(cg);
        

                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdiscountActionPerformed
        // TODO add your handling code here:
        
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + whatShow + " Military Dicount "+"$4.00");
        subnum = subnum + 4.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mdiscountActionPerformed

    
    
    private void monsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monsterActionPerformed
        // TODO add your handling code here:
                String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Monster"+"$2.75");
        subnum = subnum + 2.75 ;

        this.subtotalbox.setText(""+subnum);
        
    }//GEN-LAST:event_monsterActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        whatShow = "1stShowing";
    }//GEN-LAST:event_jButton3ActionPerformed

    private void secondShowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondShowingActionPerformed
        // TODO add your handling code here:
            whatShow = "2ndShowing";
    }//GEN-LAST:event_secondShowingActionPerformed

    private void thirdShowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdShowingActionPerformed
        // TODO add your handling code here:
         whatShow = "3rdShowing";
        
    }//GEN-LAST:event_thirdShowingActionPerformed

    private void forthShowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forthShowingActionPerformed
        // TODO add your handling code here:
        
        whatShow = "4thShowing";
    }//GEN-LAST:event_forthShowingActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
  
        String camount = this.canbox.getText();
        double incancel = Double.parseDouble(camount);
        subnum = subnum - incancel;
        this.subtotalbox.setText(""+subnum); 
        this.canbox.setText(" ");
    }//GEN-LAST:event_cancelActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sell().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buck;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField canbox;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField changebox;
    private javax.swing.JButton clear;
    private javax.swing.JButton done;
    private javax.swing.JButton fiftybucks;
    private javax.swing.JButton fivebucks;
    private javax.swing.JButton forthShowing;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kcombo;
    private javax.swing.JButton kd;
    private javax.swing.JButton kp;
    private javax.swing.JButton kr;
    private javax.swing.JButton kticket;
    private javax.swing.JButton lc;
    private javax.swing.JButton lcombo;
    private javax.swing.JButton ld;
    private javax.swing.JButton lemp;
    private javax.swing.JButton mc;
    private javax.swing.JButton md;
    private javax.swing.JButton mdiscount;
    private javax.swing.JButton memp;
    private javax.swing.JButton monster;
    private javax.swing.JButton mp;
    private javax.swing.JButton mr;
    private javax.swing.JButton rticket;
    private javax.swing.JButton sc;
    private javax.swing.JButton scombo;
    private javax.swing.JButton sd;
    private javax.swing.JButton secondShowing;
    private javax.swing.JButton semp;
    private javax.swing.JButton sp;
    private javax.swing.JButton sticket;
    private javax.swing.JTextArea subtotalarea;
    private javax.swing.JTextField subtotalbox;
    private javax.swing.JButton tenbucks;
    private javax.swing.JTextField tenderbox;
    private javax.swing.JButton thirdShowing;
    private javax.swing.JButton twentybucks;
    private javax.swing.JButton w;
    // End of variables declaration//GEN-END:variables

}

