
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package roxysoft;

import java.awt.Component;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.io.BufferedReader;
import java.io.FileReader;
import java.text.DateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import java.util.regex.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
    
    
    
    
    
    
       

    
    /**
 *
 * @author mark
 */


public class sell extends javax.swing.JFrame {
    private double subnum;
    
    
    private int indexSelect =0;
    private String whichShow = "1st Showing";
    private int ticketsSold[] = {0,0,0,0,0};
    private int ticketsLeft[] = {352,352,352,352,352};
    
    private int tempTicketCounter=0;
    
    private int ticketTotal=0;
    
    private int seatsLeft = 5;
    private int tempSeatsLeft = 0;
    
    DateFormat dateFormatL = new SimpleDateFormat("HH:mm MM/dd/yyyy");
    DateFormat dateFormatS = new SimpleDateFormat("MM/dd/yyyy");
    DateFormat dateFormatTicket = new SimpleDateFormat("MMddyy");
    Date date = new Date();
    private Component frame;
  
    /**
     * Creates new form sell
     */
    public sell() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        kd = new javax.swing.JButton();
        sd = new javax.swing.JButton();
        md = new javax.swing.JButton();
        ld = new javax.swing.JButton();
        w = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        subtotalarea = new javax.swing.JTextArea();
        kp = new javax.swing.JButton();
        sp = new javax.swing.JButton();
        mp = new javax.swing.JButton();
        sc = new javax.swing.JButton();
        mc = new javax.swing.JButton();
        lc = new javax.swing.JButton();
        lcombo = new javax.swing.JButton();
        kcombo = new javax.swing.JButton();
        scombo = new javax.swing.JButton();
        kr = new javax.swing.JButton();
        mr = new javax.swing.JButton();
        semp = new javax.swing.JButton();
        memp = new javax.swing.JButton();
        lemp = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        tenderbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        subtotalbox = new javax.swing.JTextField();
        changebox = new javax.swing.JTextField();
        buck = new javax.swing.JButton();
        twentybucks = new javax.swing.JButton();
        fivebucks = new javax.swing.JButton();
        tenbucks = new javax.swing.JButton();
        fiftybucks = new javax.swing.JButton();
        done = new javax.swing.JButton();
        rticket = new javax.swing.JButton();
        sticket = new javax.swing.JButton();
        mdiscount = new javax.swing.JButton();
        kticket = new javax.swing.JButton();
        monster = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        canbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateStamp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fifthLeft = new javax.swing.JTextField();
        thirdLeft = new javax.swing.JTextField();
        forthLeft = new javax.swing.JTextField();
        forthSold = new javax.swing.JTextField();
        secondSold = new javax.swing.JTextField();
        fifthSold = new javax.swing.JTextField();
        thirdSold = new javax.swing.JTextField();
        thirdTickNumb = new javax.swing.JTextField();
        forthTickNumb = new javax.swing.JTextField();
        firstSold = new javax.swing.JTextField();
        fifthTickNumb = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        secondLeft = new javax.swing.JTextField();
        firstLeft = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        label3 = new java.awt.Label();
        label2 = new java.awt.Label();
        secondTickNumb = new javax.swing.JTextField();
        firstTickNumb = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        tbox = new javax.swing.JTextField();
        FutureT = new javax.swing.JButton();
        futureTickets = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roxysoft");
        setFocusTraversalPolicyProvider(true);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kd.setText("Kids Drink");
        kd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdActionPerformed(evt);
            }
        });

        sd.setText("Small Drink");
        sd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdActionPerformed(evt);
            }
        });

        md.setText("Med Drink");
        md.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdActionPerformed(evt);
            }
        });

        ld.setText("Large Drink");
        ld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldActionPerformed(evt);
            }
        });

        w.setText("Water");
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });

        subtotalarea.setColumns(20);
        subtotalarea.setRows(5);
        jScrollPane1.setViewportView(subtotalarea);

        kp.setText("Kids Popcorn");
        kp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpActionPerformed(evt);
            }
        });

        sp.setText("Med Popcorn");
        sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spActionPerformed(evt);
            }
        });

        mp.setText("Large Popcorn");
        mp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpActionPerformed(evt);
            }
        });

        sc.setText("$1 Candy");
        sc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scActionPerformed(evt);
            }
        });

        mc.setText("$2 Candy");
        mc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcActionPerformed(evt);
            }
        });

        lc.setText("$3 Candy");
        lc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcActionPerformed(evt);
            }
        });

        lcombo.setText("Large Combo");
        lcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcomboActionPerformed(evt);
            }
        });

        kcombo.setText("Kids Combo");
        kcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kcomboActionPerformed(evt);
            }
        });

        scombo.setText("Super Combo");
        scombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scomboActionPerformed(evt);
            }
        });

        kr.setText("Kids refil");
        kr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krActionPerformed(evt);
            }
        });

        mr.setText("Small Med Refil");
        mr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrActionPerformed(evt);
            }
        });

        semp.setText("EMP $1");
        semp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sempActionPerformed(evt);
            }
        });

        memp.setText("EMP $2");
        memp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mempActionPerformed(evt);
            }
        });

        lemp.setText("EMP $3");
        lemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lempActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        tenderbox.setText(" ");

        jLabel1.setText("Tender");

        jLabel2.setText("Subtotal");

        jButton2.setText("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        changebox.setText(" ");

        buck.setText("$1");
        buck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buckActionPerformed(evt);
            }
        });

        twentybucks.setText("$20");
        twentybucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentybucksActionPerformed(evt);
            }
        });

        fivebucks.setText("$5");
        fivebucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivebucksActionPerformed(evt);
            }
        });

        tenbucks.setText("$10");
        tenbucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenbucksActionPerformed(evt);
            }
        });

        fiftybucks.setText("$50");
        fiftybucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiftybucksActionPerformed(evt);
            }
        });

        done.setText("Next!");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        rticket.setText("Reg Ticket");
        rticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rticketActionPerformed(evt);
            }
        });

        sticket.setText("Senior Ticket");
        sticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sticketActionPerformed(evt);
            }
        });

        mdiscount.setText("Military Ticket");
        mdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdiscountActionPerformed(evt);
            }
        });

        kticket.setText("Kids Ticket");
        kticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kticketActionPerformed(evt);
            }
        });

        monster.setText("Monster");
        monster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monsterActionPerformed(evt);
            }
        });

        cancel.setText("Subtract");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel3.setText("$ to cancel from total");

        jLabel4.setText("To null ticket, erase. Or disfigure show time and ticket type");

        dateStamp.setText("            ");
        dateStamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateStampActionPerformed(evt);
            }
        });

        jLabel5.setText("Date Stamp");

        fifthLeft.setText(" ");
        fifthLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifthLeftActionPerformed(evt);
            }
        });

        thirdLeft.setText(" ");

        forthLeft.setText(" ");

        forthSold.setText(" ");

        secondSold.setText(" ");
        secondSold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondSoldActionPerformed(evt);
            }
        });

        fifthSold.setText(" ");

        thirdSold.setText(" ");

        thirdTickNumb.setText(" ");

        forthTickNumb.setText(" ");

        firstSold.setText(" ");

        fifthTickNumb.setText(" ");

        label1.setText("Showings");

        secondLeft.setText(" ");

        firstLeft.setText(" ");

        label4.setText("Ticket Num");

        label3.setText("Sold");

        label2.setText("Left");

        secondTickNumb.setText(" ");

        firstTickNumb.setText(" ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("1st");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2nd");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("3rd");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("4th");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("5th");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Ticket Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(firstLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                            .addComponent(firstSold)
                                            .addComponent(firstTickNumb))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(secondTickNumb, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                                .addComponent(secondSold, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(secondLeft, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jRadioButton2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton3)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(thirdSold, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                                .addComponent(thirdLeft, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(thirdTickNumb))))
                                    .addComponent(jRadioButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(forthSold, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                            .addComponent(forthTickNumb, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(forthLeft))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButton4)
                                        .addGap(29, 29, 29)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fifthLeft)
                                    .addComponent(fifthSold, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fifthTickNumb, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jRadioButton5)
                                        .addGap(0, 34, Short.MAX_VALUE)))
                                .addGap(36, 36, 36)))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(firstSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(secondSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(thirdSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(forthSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fifthSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(firstTickNumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(secondTickNumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(thirdTickNumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(forthTickNumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fifthTickNumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButton2)
                                .addComponent(jRadioButton3))
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton4)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(secondLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thirdLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(forthLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fifthLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        label1.getAccessibleContext().setAccessibleName("label1");

        label5.setText("Ticket numbers are organized month, day, year, showing, and ticket number.");

        tbox.setText("         ");
        tbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tboxActionPerformed(evt);
            }
        });

        FutureT.setText("Future ticket");

        futureTickets.setText("    ");
        futureTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                futureTicketsActionPerformed(evt);
            }
        });

        jLabel7.setText("Name desired date & showtime. # of Tickets ");

        jMenu1.setText("ROXYSOFT");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configure Movie");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(md, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ld, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(monster)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(futureTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(100, 100, 100)
                                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(FutureT)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(sp)
                                        .addGap(175, 175, 175)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(kticket, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(mdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(sticket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(rticket, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addComponent(jScrollPane1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(260, 260, 260)
                                        .addComponent(mp)
                                        .addGap(41, 41, 41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(semp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(memp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lemp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kr, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mr, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(lc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(scombo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(kcombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(795, 795, 795))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(tbox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19)
                                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(70, 70, 70)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(buck, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(fivebucks, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(1, 1, 1)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(twentybucks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(subtotalbox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(tenbucks, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(tenderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2))
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cancel)
                                                    .addComponent(canbox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fiftybucks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(changebox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(40, 40, 40))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(434, 434, 434)))))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lemp, memp, semp});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {kd, kp, lc, ld, mc, md, mp, sc, sd, sp});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(md, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(ld, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(monster, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(w, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(FutureT)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(futureTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rticket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sticket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kticket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buck)
                            .addComponent(tenbucks)
                            .addComponent(jLabel1)
                            .addComponent(canbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(semp)
                                    .addComponent(memp)
                                    .addComponent(lemp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kr)
                                    .addComponent(mr)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(scombo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(twentybucks)
                        .addComponent(fivebucks)
                        .addComponent(subtotalbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cancel))
                    .addComponent(dateStamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(fiftybucks)
                            .addComponent(changebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {kcombo, kd, kp, lc, ld, mc, md, mp, sc, sd, sp});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lemp, memp, semp});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {kticket, mdiscount, rticket, sticket});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:

        this.tenderbox.setText(" ");
        this.subtotalbox.setText(" ");
        this.subtotalarea.setText(" ");
        this.changebox.setText(" ");
        tempTicketCounter = 0;
        subnum=0;
        
    }//GEN-LAST:event_clearActionPerformed

    private void mrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "small medium refill "+"$1.00");
        subnum = subnum + 1.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mrActionPerformed

    private void krActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Kids refil "+"$0.50");
        subnum = subnum + 0.50 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_krActionPerformed

    private void fiftybucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiftybucksActionPerformed
        // TODO add your handling code here:
        Double tbox = 50.00;
        this.tenderbox.setText(""+tbox);
    }//GEN-LAST:event_fiftybucksActionPerformed

    private void twentybucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentybucksActionPerformed
        // TODO add your handling code here:
        Double tbox = 20.00;
        this.tenderbox.setText(""+tbox);
    }//GEN-LAST:event_twentybucksActionPerformed

    private void kticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kticketActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + whichShow + " Kids "+"$0.00");
        subnum = subnum + 0.00 ;
        tempTicketCounter++;
        tempSeatsLeft++;
        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_kticketActionPerformed

    private void sticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sticketActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + whichShow + " Senior Ticket "+"$4.00");
        subnum = subnum + 4.00 ;
        tempTicketCounter++;
        tempSeatsLeft++;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_sticketActionPerformed

    private void rticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rticketActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + whichShow +" Regular Ticket "+"$5.00");
        subnum = subnum + 5.00 ;
        tempTicketCounter++;
        tempSeatsLeft++;
        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_rticketActionPerformed

    private void lempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lempActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$3.00 EMP "+"$1.50");
        subnum = subnum + 1.50 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_lempActionPerformed

    private void mempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mempActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$2.00 EMP"+"$1.00");
        subnum = subnum + 1.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mempActionPerformed

    private void sempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sempActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$1:00 EMP"+"$.50");
        subnum = subnum + 0.50 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_sempActionPerformed

    private void scomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scomboActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Super Combo "+"$10.00");
        subnum = subnum + 10;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_scomboActionPerformed

    private void lcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcomboActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Large Combo "+"$7.75");
        subnum = subnum + 7.75 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_lcomboActionPerformed

    private void kcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kcomboActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Kids Combo "+"$3.25");
        subnum = subnum + 3.25 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_kcomboActionPerformed

    private void lcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$3.00 Candy "+"$3.00");
        subnum = subnum + 3.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_lcActionPerformed

    private void mcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$2.00 Candy "+"$2.00");
        subnum = subnum + 2.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mcActionPerformed

    private void scActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "$1.00 Candy "+"$1.00");
        subnum = subnum + 1.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_scActionPerformed

    private void kpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kpActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Kids Popcorn "+"$1.75");
        subnum = subnum + 1.75 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_kpActionPerformed

    private void spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Med Popcorn "+"$4.00");
        subnum = subnum + 4.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_spActionPerformed

    private void mpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Large Popcorn "+"$4.50");
        subnum = subnum + 4.50;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mpActionPerformed

    private void wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Water "+"$1.25");
        subnum = subnum + 1.25 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_wActionPerformed

    private void ldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Large Drink "+"$4.00");
        subnum = subnum + 4.00 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_ldActionPerformed

    private void mdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Med Drink "+"$3.50");
        subnum = subnum + 3.50;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mdActionPerformed

    private void sdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdActionPerformed
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Small Drink "+"$2.75");
        subnum = subnum + 2.75 ;

        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_sdActionPerformed

    private void kdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdActionPerformed
        // TODO add your handling code here:
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Kids Drink "+"$1.25");
        subnum = subnum + 1.25 ;

        this.subtotalbox.setText(" "+subnum);
    }//GEN-LAST:event_kdActionPerformed

    private void tenbucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenbucksActionPerformed
        // TODO add your handling code here:
        Double tbox = 10.00;
        this.tenderbox.setText(""+tbox);
    }//GEN-LAST:event_tenbucksActionPerformed

    private void fivebucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivebucksActionPerformed
        // TODO add your handling code here:
        Double tbox = 5.00;
        this.tenderbox.setText(""+tbox);
    }//GEN-LAST:event_fivebucksActionPerformed

    private void buckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buckActionPerformed
        // TODO add your handling code here:
        Double tbox = 1.00;
        this.tenderbox.setText(""+tbox);
    }//GEN-LAST:event_buckActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        PrintWriter out = null;
        try {
            out = new PrintWriter(new FileWriter("roxyrecord.txt", true));
           //worked! works! Whooot
  
            
            
            ticketsSold[indexSelect] = tempTicketCounter;
            System.out.println(generateTicketCode());
            fillInTicketsLeft();
            fillInBoxTicketNumber();
            fillInBoxTicketCode();

            
            String subbtt = this.subtotalarea.getText();
            String stuff =subbtt+"\n"+"\n"+"SubTotal:"+subnum;
            out.println(stuff+" "+dateFormatL.format(date)+" "+ generateTicketCode());
            out.close();
            ticketsLeft[indexSelect] = ticketsLeft[indexSelect]-tempSeatsLeft;
            
           ticketTotal=ticketsSold[0]+ticketsSold[1]+ticketsSold[2]+ticketsSold[3]+ticketsSold[4];
           this.tbox.setText(String.valueOf(ticketTotal));
           
           
           
            if(seatsLeft < 1){
                
                   JOptionPane.showMessageDialog(frame,
                 "There are no more seats left",
                  "Inane warning",
                  JOptionPane.WARNING_MESSAGE);
            }
            
            
            
            this.tenderbox.setText(" ");
            this.subtotalbox.setText(" ");
            this.subtotalarea.setText(" ");
            this.changebox.setText(" ");
            
            
            subnum=0;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(sell.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(sell.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_doneActionPerformed
     void fillInBoxTicketNumber(){
        if(indexSelect == 0){
        this.firstSold.setText(generateTicketNumber());
         }
         if(indexSelect == 1){
         this.secondSold.setText(generateTicketNumber());
         }
         if(indexSelect == 2){
         this.thirdSold.setText(generateTicketNumber());
         }
         if(indexSelect == 3){
         this.forthSold.setText(generateTicketNumber());
         }
         if(indexSelect == 4){
         this.fifthSold.setText(generateTicketNumber());
         }
        
    }
 
 
    void fillInTicketsLeft(){
        if(indexSelect == 0){
     this.firstLeft.setText(Integer.toString(ticketsLeft[indexSelect]));
         }
         if(indexSelect == 1){
     this.secondLeft.setText(Integer.toString(ticketsLeft[indexSelect]));
         }
         if(indexSelect == 2){
     this.thirdLeft.setText(Integer.toString(ticketsLeft[indexSelect]));
         }
         if(indexSelect == 3){
     this.forthLeft.setText(Integer.toString(ticketsLeft[indexSelect]));
         }
         if(indexSelect == 4){
     this.fifthLeft.setText(Integer.toString(ticketsLeft[indexSelect]));
         }
        
    }
     void fillInBoxTicketCode(){
         if(indexSelect == 0){
     this.firstTickNumb.setText(generateTicketCode());
         }
         if(indexSelect == 1){
     this.secondTickNumb.setText(generateTicketCode());
         }
         if(indexSelect == 2){
     this.thirdTickNumb.setText(generateTicketCode());
         }
         if(indexSelect == 3){
     this.forthTickNumb.setText(generateTicketCode());
         }
         if(indexSelect == 4){
     this.fifthTickNumb.setText(generateTicketCode());
         }
     
     }
    
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // This is the Change button Sorry
                  String t;
                  String m;
                  Double chg;
                  t = this.tenderbox.getText();
                  m = this.subtotalbox.getText();
                 Double dObj1 = new Double(t);
                 Double dObj2 = new Double(m);
                  
                 chg = dObj1-dObj2;
                 
               String cg = Double.toString(chg);
                this.changebox.setText(cg);
        

                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdiscountActionPerformed
        // TODO add your handling code here:
        
        String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + whichShow + " Military Dicount "+"$4.00");
        subnum = subnum + 4.00 ;
        tempTicketCounter++;
        seatsLeft++;
        this.subtotalbox.setText(""+subnum);
    }//GEN-LAST:event_mdiscountActionPerformed

    
    
    private void monsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monsterActionPerformed
        // TODO add your handling code here:
                String subt = this.subtotalarea.getText();
        this.subtotalarea.setText(subt+"\n" + "Monster"+"$2.75");
        subnum = subnum + 2.75 ;

        this.subtotalbox.setText(""+subnum);
        
    }//GEN-LAST:event_monsterActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
  
        String camount = this.canbox.getText();
        double incancel = Double.parseDouble(camount);
        subnum = subnum - incancel;
        this.subtotalbox.setText(""+subnum); 
        this.canbox.setText(" ");
    }//GEN-LAST:event_cancelActionPerformed

    private void dateStampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateStampActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dateStampActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
       // This set's the show array to 1
        // That is it's recording for the first show
        indexSelect = 0;
        whichShow = "1st Showing";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        
        indexSelect = 1;
        whichShow = "2nd Showing";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        indexSelect = 2;
        whichShow = "3rd Showing";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        indexSelect = 3;
        whichShow = "4th Showing";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        indexSelect = 4;
        whichShow = "5th Showing";
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void fifthLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifthLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fifthLeftActionPerformed

    private void secondSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondSoldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondSoldActionPerformed

    private void tboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tboxActionPerformed

    private void futureTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_futureTicketsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_futureTicketsActionPerformed

    
    private String generateTicketCode(){
        
            String a = Integer.toString(indexSelect+1);
       String answer = dateFormatTicket.format(date)+a+"00"+ticketsSold[indexSelect];
       return answer;
        }
    private String generateTicketNumber(){
        
            String a = Integer.toString(indexSelect+1);
       String answer = Integer.toString(ticketsSold[indexSelect]);
       return answer;
        }
    
            
    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("empty-statement")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sell().setVisible(true);
            }
        });
        
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FutureT;
    private javax.swing.JButton buck;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JTextField canbox;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField changebox;
    private javax.swing.JButton clear;
    private javax.swing.JTextField dateStamp;
    private javax.swing.JButton done;
    private javax.swing.JTextField fifthLeft;
    private javax.swing.JTextField fifthSold;
    private javax.swing.JTextField fifthTickNumb;
    private javax.swing.JButton fiftybucks;
    private javax.swing.JTextField firstLeft;
    private javax.swing.JTextField firstSold;
    private javax.swing.JTextField firstTickNumb;
    private javax.swing.JButton fivebucks;
    private javax.swing.JTextField forthLeft;
    private javax.swing.JTextField forthSold;
    private javax.swing.JTextField forthTickNumb;
    private javax.swing.JTextField futureTickets;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kcombo;
    private javax.swing.JButton kd;
    private javax.swing.JButton kp;
    private javax.swing.JButton kr;
    private javax.swing.JButton kticket;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JButton lc;
    private javax.swing.JButton lcombo;
    private javax.swing.JButton ld;
    private javax.swing.JButton lemp;
    private javax.swing.JButton mc;
    private javax.swing.JButton md;
    private javax.swing.JButton mdiscount;
    private javax.swing.JButton memp;
    private javax.swing.JButton monster;
    private javax.swing.JButton mp;
    private javax.swing.JButton mr;
    private javax.swing.JButton rticket;
    private javax.swing.JButton sc;
    private javax.swing.JButton scombo;
    private javax.swing.JButton sd;
    private javax.swing.JTextField secondLeft;
    private javax.swing.JTextField secondSold;
    private javax.swing.JTextField secondTickNumb;
    private javax.swing.JButton semp;
    private javax.swing.JButton sp;
    private javax.swing.JButton sticket;
    private javax.swing.JTextArea subtotalarea;
    private javax.swing.JTextField subtotalbox;
    private javax.swing.JTextField tbox;
    private javax.swing.JButton tenbucks;
    private javax.swing.JTextField tenderbox;
    private javax.swing.JTextField thirdLeft;
    private javax.swing.JTextField thirdSold;
    private javax.swing.JTextField thirdTickNumb;
    private javax.swing.JButton twentybucks;
    private javax.swing.JButton w;
    // End of variables declaration//GEN-END:variables

}

